Got rid of fuzzel for tofi

diff --git a/scripts/media/movie-watch b/scripts/media/movie-watch
--- a/scripts/media/movie-watch
+++ b/scripts/media/movie-watch
@@ -3,8 +3,8 @@
 # Define the directory containing media files
 media_dir=~/Data/Media/Movies
 
-# Check if fuzzel and mpv are installed
-command -v fuzzel >/dev/null 2>&1 || { echo >&2 "fuzzel is required but not installed. Aborting."; exit 1; }
+# Check if tofi and mpv are installed
+command -v tofi >/dev/null 2>&1 || { echo >&2 "tofi is required but not installed. Aborting."; exit 1; }
 command -v mpv >/dev/null 2>&1 || { echo >&2 "mpv is required but not installed. Aborting."; exit 1; }
 
 # Change working directory to the media directory
@@ -13,8 +13,8 @@ cd "$media_dir" || { echo >&2 "Unable to change directory to $media_dir. Abortin
 # Use find to recursively list all media files in the specified directory
 media_files=$(find . -type f \( -iname "*.mp4" -o -iname "*.mkv" -o -iname "*.avi" -o -iname "*.mp3" -o -iname "*.flac" \) | sed 's|^\./||')
 
-# Use dmenu to display the list of media files and get user input
-selected_file=$(echo "$media_files" | fuzzel --dmenu -p "Select a media file:")
+# Use tofi to display the list of media files and get user input
+selected_file=$(echo "$media_files" | tofi --prompt-text "Select a media file:")
 
 # Check if the user selected a file
 if [ -n "$selected_file" ]; then
diff --git a/scripts/read-book b/scripts/read-book
--- a/scripts/read-book
+++ b/scripts/read-book
@@ -3,8 +3,8 @@
 # Define the directory containing Book files
 media_dir=~/Data/Media/Books
 
-# Check if fuzzel and zahutra are installed
-command -v fuzzel >/dev/null 2>&1 || { echo >&2 "fuzzel is required but not installed. Aborting."; exit 1; }
+# Check if tofi and zahutra are installed
+command -v tofi >/dev/null 2>&1 || { echo >&2 "tofi is required but not installed. Aborting."; exit 1; }
 command -v zathura >/dev/null 2>&1 || { echo >&2 "zathura is required but not installed. Aborting."; exit 1; }
 
 # Change working directory to the Books directory
@@ -13,8 +13,8 @@ cd "$media_dir" || { echo >&2 "Unable to change directory to $media_dir. Abortin
 # Use find to recursively list all Books files in the specified directory
 media_files=$(find . -type f \( -iname "*.pdf" -o -iname "*.epub" -o -iname "*.docx" -o -iname "*.cb" -o -iname "*.odt" \) | sed 's|^\./||')
 
-# Use fuzzel to display the list of Books files and get user input
-selected_file=$(echo "$media_files" | fuzzel --dmenu -l 10 -p "Select a Book:")
+# Use tofi to display the list of Books files and get user input
+selected_file=$(echo "$media_files" | tofi --prompt-text "Select a Book:")
 
 # Check if the user selected a file
 if [ -n "$selected_file" ]; then
