added new scripts and changed few

diff --git a/scripts/media/movie-watch b/scripts/media/movie-watch
--- a/scripts/media/movie-watch
+++ b/scripts/media/movie-watch
@@ -1,11 +1,23 @@
-#!/bin/bash
+#!/bin/sh
 
-path="$HOME/Data/Media/Movies/"
+# Define the directory containing media files
+media_dir=~/Data/Media/Movies
 
-media="$(fd --base-directory $path --full-path "$path" | tofi --prompt-text "Select the Media: ")"
+# Check if fuzzel and mpv are installed
+command -v fuzzel >/dev/null 2>&1 || { echo >&2 "fuzzel is required but not installed. Aborting."; exit 1; }
+command -v mpv >/dev/null 2>&1 || { echo >&2 "mpv is required but not installed. Aborting."; exit 1; }
 
-if [ -z "$media" ]; then
-	exit 0
-else
-	setsid -f mpv $path/"$media"
+# Change working directory to the media directory
+cd "$media_dir" || { echo >&2 "Unable to change directory to $media_dir. Aborting."; exit 1; }
+
+# Use find to recursively list all media files in the specified directory
+media_files=$(find . -type f \( -iname "*.mp4" -o -iname "*.mkv" -o -iname "*.avi" -o -iname "*.mp3" -o -iname "*.flac" \) | sed 's|^\./||')
+
+# Use dmenu to display the list of media files and get user input
+selected_file=$(echo "$media_files" | fuzzel --dmenu -p "Select a media file:")
+
+# Check if the user selected a file
+if [ -n "$selected_file" ]; then
+    # Use mpv to play the selected file
+    mpv "$selected_file"
 fi
diff --git a/scripts/read-book b/scripts/read-book
--- a/scripts/read-book
+++ b/scripts/read-book
@@ -1,11 +1,23 @@
 #!/bin/sh
 
-books="$HOME/Data/Media/Books/"
+# Define the directory containing Book files
+media_dir=~/Data/Media/Books
 
-read="$(fd --base-directory $books --full-path "$books" | tofi --prompt-text "Select the Book: ")"
+# Check if fuzzel and zahutra are installed
+command -v fuzzel >/dev/null 2>&1 || { echo >&2 "fuzzel is required but not installed. Aborting."; exit 1; }
+command -v zathura >/dev/null 2>&1 || { echo >&2 "zathura is required but not installed. Aborting."; exit 1; }
 
-if [ -z "$read" ]; then
-	exit 0
-else
-	setsid -f zathura $books/"$read"
+# Change working directory to the Books directory
+cd "$media_dir" || { echo >&2 "Unable to change directory to $media_dir. Aborting."; exit 1; }
+
+# Use find to recursively list all Books files in the specified directory
+media_files=$(find . -type f \( -iname "*.pdf" -o -iname "*.epub" -o -iname "*.docx" -o -iname "*.cb" -o -iname "*.odt" \) | sed 's|^\./||')
+
+# Use fuzzel to display the list of Books files and get user input
+selected_file=$(echo "$media_files" | fuzzel --dmenu -l 10 -p "Select a Book:")
+
+# Check if the user selected a file
+if [ -n "$selected_file" ]; then
+    # Use zathura to open the selected file
+    zathura "$selected_file"
 fi
